language: elixir
sudo: required
cache:
  directories:
    - deps
    - _build
services:
  - docker
elixir:
  - 1.7.4
otp_release:
  - 21.2.5
addons:
  apt:
    packages:
      - docker-ce
notifications:
  slack:
    rooms:
      - secure: "dOmFhHBd3d+wIiMe6tiHJ31WwmpnZlWRzGl67OVpnDK1IJrvi1BYv8c6H6Elm9QBEFcWARDXVzOeTbAffPS+IK521ntNpuawzOzTNCyPaKcbcSF/Q2QyVHAS8vplmE091lVPNQG3A4lYnAXImjElTL5/ZNGqseQjsSnSMustTASSw7WMSNRkeD5Ad7C8nZGD1QQ05eQVrYB2AcTrzHKdrmNdY+++fJr1P5bKTjfYlMEV8f/zP/hmqUAbe8B/jGkY9oDOVr9BpXNyfof5azdR7FBUtkdZQYtmwLDHViH8YU0eY7KQlsZqbqiyTrtNL3TGVTFAqQsnFUF/MYf5AM18tBqiZT9+7aV/2px+yxqGsYultIDu7x+VkiqU3xsfzARkLP+HrDQsifiYxu0V7yGqAo89VknGffXRilEgK47M9FVOGwkK2jYiYk3PnCiwPSRJCQnpfs6RpVr6Pa2Aw/VuYbhQ8dPXeH7Q13lFiUgsyBPco3duwtI0v5mzwwzjdN8OJuroJO9wQbUurfG+rggWPRlKAaHOqEDApZWN7x2v+LSVYIG3sg9c83Z9NcaqjP0hKQzF5BkUXOu9BcsGGqmKlVC2DMyUVT2ppQ3OphGqBODP1Wpasw6U508X2+QRtvWAOakKqiRlthaMLKkRZbMHmFaHVYihC8IBVrxpTDygpDo="
    on_success: always
env:
  global:
    - MIX_ENV=test
    - DOCKER_HUB_ACCOUNT=edenlabllc
    - OBJECT_STORAGE_BACKEND="gcs"
    - AWS_REGION=us-east-1
    - DOCKER_NAMESPACE=edenlabllc
    - APPS='[{"app":"ael_api","chart":"ael","namespace":"ael","deployment":"api","label":"api"}]'
    - POSTGRES_VERSION=9.6
      # DOCKER
    - secure:  "m1f/RLiyjbS4QVG530OmSVnxhOuTvUVnACgR0yr7v7FYl7nxFrqXrTFeV/vSvR0LJZx1CoaVtTZUFFdyKuOyfxUq5FjYXcOLlQAnzNAqpQSzXEcaMujKiFW9pgebXztdqCJbxrKQYs8r/Lp7GJyW1Gt4gE8wl+BPt3s9d4cvh2xNERUNsejV7MGl6XUg0uAq3kOi3iBBWkJrWpS5oHMnK6+PjUb05af0xmkC1gU+ec/ZeslAw4iXY5+hyCoYkZvt4CPxRs8Cmx4yO1cHIU6JDHV/zNkJQqCxsFSJmMR/vAzz/w5JakY9B7y99N5NrcMBJrivGvhELvo4XgeCLJlRz4+ZRb8/nJG+v/t53nM6yw1ZggsujkF9qAuqmTaJFgAD2wnx4OS6CPxb4sz8SInmfU5i6D6IOhZ112Qjn3lsk5r4YMMvL14lHYktlgm9PJ1g1EOo+G9nqWmXIvBSHelVpAF8iYrMhMSvdDnSN0sd/jWRIecWfULGoH+b5WQaByYncRQql5vwp4VViwyYXj9vcv/I3ylPRLz1BV9lODaDAJNHtxBl8LloJbpBUk9CuJzzpmOwQqerd5wm3g/RD+i/PD3581mGLs8HfmlLf6KbnQEkmGIehRudpqji4PU4ds+o/wCS8Hpdua4jNN6nLuSIDNz1swuWuopjvaNKcfeXAqQ="
branches:
  # Releases are generated automatically, stop infinite build loop
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  - sudo apt-get install jq
  - openssl aes-256-cbc -K $encrypted_41496dbc4a59_key -iv $encrypted_41496dbc4a59_iv -in priv/secret.enc -out priv/service_account_key.json -d
  - curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/init-db.sh -o init-db.sh; sudo sh ./init-db.sh
jobs:
  include:
    - stage: "test and build"
      name: "test"
      # run tests
      script: (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/tests.sh -o tests.sh; bash ./tests.sh) || travis_terminate 1
      # Build Docker container
    - stage: "test and build"
      name: "ael_api"
      env:
        - DB_MIGRATE=true
        - APPS='[{"app":"ael_api","label":"api","namespace":"ael","chart":"ael", "deployment":"api"}]'
      # "Decrypting deploy key..."
      script:
      - openssl aes-256-cbc -K $encrypted_69844ac3575d_key -iv $encrypted_69844ac3575d_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
      - (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/docker.sh -o docker.sh; bash ./docker.sh) || travis_terminate 1
